### ISSUE TITLE
Server supports up to '1024' concurrent connections.

### ISSUE THREAD

**Issue by ghost** [VirtualEstatePlanner/Tritogeneia#1]
HI,

tried to raise this limit inside the docker.
And I didn't find a way.
Do you know how to do it?

Thanks

**Comment by VirtualEstatePlanner** [comment]
I was actually doing this to try to prove to a girl I was dating that Docker had practical implications for non-server users.  She was an RO player, and I decided to show her that it would be easy for a player to set up a server, but she lost interest in the idea, so I stopped.  I can maybe answer a few questions for you, but this project is both incomplete and abandoned.  Feel free to fork the project.  If you do, please send me a link, I’d like to see what you do with it.
- VirtualEstatePlanner

**Comment by VirtualEstatePlanner** [comment]
project is abandoned
